name: Build Sprite Stacking with Pygbag
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deploy:
    name: Sprite Stacking Game
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        echo "Installing dependencies..."
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install pygame-ce pygbag
        echo "Dependencies installed successfully."
        
    - name: List workspace content
      run: |
        echo "Listing workspace content:"
        ls -la $GITHUB_WORKSPACE/src
        
    - name: Prepare assets for web build
      run: |
        echo "Preparing assets for web build..."
        mkdir -p $GITHUB_WORKSPACE/src/assets
        cp -r $GITHUB_WORKSPACE/assets/* $GITHUB_WORKSPACE/src/assets/
        echo "Assets prepared. Content of src directory:"
        ls -la $GITHUB_WORKSPACE/src
        echo "Content of src/assets directory:"
        ls -la $GITHUB_WORKSPACE/src/assets
        
    - name: Build with Pygbag
      run: |
        echo "Building with pygbag..."
        cd $GITHUB_WORKSPACE
        python -m pygbag --build src/main.py
        echo "Build complete - checking output:"
        ls -la src/build/web

    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'src/build/web'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4